### ISSUE TITLE
Research connecting GitHub and TravisCI

### ISSUE THREAD

**Issue by nischayv** [hammer-io/hammer-cli#30]
- [ ] Research how to set up GitHub and TravisCI to work together automatically

**Comment by KrashLeviathan** [comment]
Resource: https://docs.travis-ci.com/api/

**Comment by KrashLeviathan** [comment]
### Using the Travis CLI

https://github.com/travis-ci/travis.rb

```
travis login
travis enable -r <github username>/<project name>
```

### Results

- https://github.com/KrashLeviathan/BLAH
- https://travis-ci.org/KrashLeviathan/BLAH

**Comment by KrashLeviathan** [comment]
#31 (CLI should generate basic mocha test structure) needs to be completed before we setup and enable Travis on a new project
